name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Criar .env
      run: |
        echo "BASE_URL_REST=${{ secrets.BASE_URL_REST }}" >> .env
        echo "BASE_URL_GRAPHQL=${{ secrets.BASE_URL_GRAPHQL }}" >> .env
<<<<<<< HEAD

    - name: Verificar conteúdo do .env (debug)
      run: cat .env

    - name: Rodar os testes de API REST via Controller
      run: npm run test-rest-controller
=======
>>>>>>> 0fde03cb3ae640fdd59acb46cfead006ab7c4783

    - name: Rodar os testes de API REST via Controller
      run: npm run test-rest-controller

    - name: Subir a API REST
      run: npm run start-rest &

    - name: Subir a API GraphQL
      run: npm run start-graphql &
      
    - name: Esperar a API estar Funcionando
      run: sleep 8
   
    - name: Rodar os testes de API REST externo via HTTP
      run: npm run test-rest-external
  
    - name: Rodar os testes de API GraphQL externo via HTTP
      run: npm run test-graphql-external
      